### ISSUE TITLE
How should I build RegionToXaero in IDEA?

### ISSUE THREAD

**Issue by LeonYew-Ley** [Entropy5/JMtoXaero#11]
Dear Developer, 
Pls forgive me a new guy to use this tool, I need to convert my singleplayer region to multi-player xaeromap, how should I build RegionToXaero.java into a jar?
please, thank u.  : )

**Comment by Entropy5** [comment]
I searched my old folders for a jar and added it to [release 2.2](https://github.com/Entropy5/JMtoXaero/releases/tag/2.2)
you can run it yourself in an IDE, without ever making a jar as well
if youre not on 1.12 then this wont work lol

**Comment by LeonYew-Ley** [comment]
thanks, the previous project is worked on eclipse after I installed JDK 1.8. And it worked perfectly on 1.12 , however, due to the block updates on 1.20, those NBT lib can't recognize the new blocks : ( 
Anyway, wonderful tool ! Hope u update it when u have time.

**Comment by Entropy5** [comment]
i made this project just to convert my own data and made it public so others could try the same
if i ever find a relevant use for regiontoxaero in new updates then i might update it, but i wont make promises

you can always try it yourself :p
you only need a region reader plugin and decompiled xaero jars

some documentation on xaeros format is here https://github.com/DanDucky/XaerotoJourneyMap
