### ISSUE TITLE
Issue when converting maps on linux

### ISSUE THREAD

**Issue by Moot-a** [Entropy5/JMtoXaero#12]
Hi, thanks for the mod!

I tried following your guide on my linux computer, and here's the problems I have :

```bash
$java -jar JMtoXaero-3.0.jar "~/.local/share/PrismLauncher/instances/Fabulously Optimized/.minecraft/journeymap/data/mp/<serverName>" "~/.local/share/PrismLauncher/instances/Fabulously Optimized/.minecraft/XaeroWorldMap/<serverName>" all

Processing dimension: the_nether
Exception in thread "main" java.io.IOException: input folder doesn't exist
        at com.github.entropy5.JourneyMapToXaero.processDimension(JourneyMapToXaero.java:137)
        at com.github.entropy5.JourneyMapToXaero.main(JourneyMapToXaero.java:63)
```

It seems to make this error with every dimensions, I guess I'll copy these files on a windows vm and report back.

**Comment by Moot-a** [comment]
Still doesn't work on windows, might be because the server is in 1.20.6.

**Comment by Moot-a** [comment]
Finally I used XearoPlus, sorry for the inconvenience.

Take care!

**Comment by Entropy5** [comment]
The `<serverName>` part in your first location doesnt seem right to me
This tool was also made for 1.12 and JM has changed folder names since then
which can be bypassed with https://github.com/Entropy5/JMtoXaero/issues/8
