### ISSUE TITLE
Running then crashing

### ISSUE THREAD

**Issue by NathanVH8** [Entropy5/JMtoXaero#4]
I've tried using JMtoXaero-2.0 (From the releases page) with three different versions of Java (Java 8, 11, and 17) but each time I get this same error. Any idea of what's going on?
```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at com.github.entropy5.JourneyMapToXaero.processDimension(JourneyMapToXaero.java:170)
	at com.github.entropy5.JourneyMapToXaero.main(JourneyMapToXaero.java:39)
```

**Comment by Entropy5** [comment]
can you give the entire command you used and make sure that there are journeymap image files in the source folder

**Comment by NathanVH8** [comment]
I was using `java -jar JMtoXaero-2.0.jar "[source_folder]/" "Xaeromap/" 1` with the two referenced folders in the same directory as the jar file. And the source folder contains `overworld`, `the_end`, and `waypoints`

**Comment by Entropy5** [comment]
Try using full paths maybe (starting with C:/user)
The output folder can basically be empty
But my input folders look like this, with the DIM names and never the word "overworld"
DIM0 is overworld and DIM1 is end
What version of journeymap are you running?
![image](https://user-images.githubusercontent.com/44469915/177022010-d06a9915-5700-4e55-bd47-5874c234dd40.png)

**Comment by NathanVH8** [comment]
JourneyMap version is JourneyMap 1.18.2 5.8.4 fabric, and I have now tried full paths, but it still didn't work.
Also, I'm running it on Xubuntu 18.04, not Windows.

**Comment by Entropy5** [comment]
This tool was designed for 1.12 mods
It only looks for the DIM folders
rename overworld to DIM0 and the_end to DIM1

**Comment by NathanVH8** [comment]
Ugh, I figured out what it was. I was trying to convert DIM1 which is the nether, but there were no files for the nether.
I was being an idiot and forgot that DIM0 is the overworld. Once I figured that out, it's working perfectly.

**Comment by Entropy5** [comment]
nether is DIM-1 (the _under_world)
I should probably clarify this in readme better
